### ISSUE TITLE
add deal specs page to front end

### ISSUE THREAD

**Issue by ita-c** [banyancomputer/estuary-www#8]
include deal start, deal end, last proof, etc.

**Comment by amiller68** [comment]
Implemented a deals page, where users should be able to pull deal specifics off-chain. This needs to be integrated with a proper ABI that we define next sprint.

**Comment by ita-c** [comment]
do we integrate next sprint or just define?

**Comment by amiller68** [comment]
I guess define (Marco's code still needs to be refactored in Master), implement (What I have now is failing, and I'm not sure why, so this needs to be debugged once we refactor the ABI), and test.  that doesn't necessarily involve integration you're right.

**Comment by ita-c** [comment]
do open issues cover this?
